name: topiary
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - numpy<1.22
  - pandas
  - xlrd
  - openpyxl
  - matplotlib
  - biopython
  - tqdm
  - ete3
  - dendropy
  - toytree
  # - blast    # [not osx]
  # - muscle   # [not osx]
  # - generax  # [not osx]
  # - raxml-ng # [not osx]
  - pip
  - pip:
    - pastml
    - opentree
