name: topiary
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - xlrd
  - openpyxl
  - tqdm
  - ete3
  - dendropy
  - toytree
  - pip:
    - pastml
  - blast # [not win] 
  - muscle # [not win]
  - generax # [not win]
  - raxml-ng # [not win]
