name: topiary
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pandas
  - xlrd
  - openpyxl
  - matplotlib
  - biopython
  - tqdm
  - ete3
  - dendropy
  - toytree
  - pastml
  #- openmpi<4.1.3
  #- blast    # [not win]
  #- muscle   # [not win]
  #- generax  # [not win]
  #- raxml-ng # [not win]
  #- mpi4py
  - pip
  - pip:
  #  - pastml==1.9.34
    - opentree
