name: topiary
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - xlrd
  - openpyxl
  - tqdm
  - ete3
  - dendropy
  - toytree
  - ghostscript
#  - blast
#  - generax
#  - muscle
#  - raxml-ng
