name: topiary
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - openpyxl
  - xlrd
  - pytest
  - pandas
  - numpy
  - jupyter
  - tqdm
  - blast
  - generax
  - muscle
  - raxml-ng
  - toytree
  - ghostscript
