{% set name = "topiary-asr" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/harmslab/topiary/releases/download/{{ version }}/topiary-{{ version }}.tar.gz
  sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge``

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python
    - pip
  skip: True #[py<38]
  run:
    - python
    - numpy<1.22
    - pandas
    - xlrd
    - openpyxl
    - matplotlib
    - biopython
    - tqdm
    - ete3
    - dendropy
    - toytree
    - blast>=2.2    #[not osx and not arm64]
    - muscle>=5.0   #[not osx and not arm64]
    - openmpi<4.1.3 #[not osx and not arm64]
    - generax>=2.0  #[not osx and not arm64]
    - raxml-ng>=1.1 #[not osx and not arm64]
    - pip
    - pip:
      - pastml
      - opentree

test:
  imports:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simplejson/simplejson
  summary: 'Python framework for doing ancestral sequence reconstruction.'
  description: |
    Python framework for doing ancestral sequence reconstruction. Performs
    sequence database construction, quality control, multiple sequence
    alignment, tree construction, gene/species tree reconciliation, and
    ancestral reconstruction with minimal user input.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://topiary-asr.readthedocs.io/
  dev_url: https://github.com/harmslab/topiary/

extra:
  recipe-maintainers:
    - harmsm
