# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: topiary

on:
  push:
    branches: [ main   ]
  pull_request:
    branches: [ main   ]

jobs:
  build-nix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9' ]
    steps:
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Checkout
      uses: actions/checkout@v3.0.0
      with:
        repository: harmsm/topiary
        path: topiary

    - name: Install topiary, run flake8, run pytest
      shell: bash
      run: |
        cd topiary

        $CONDA/bin/conda env create --file environment.yml
        $CONDA/bin/conda activate topiary || true
        export PATH=$CONDA/envs/topiary/bin:$PATH

        $CONDA/bin/conda install flake8
        $CONDA/bin/conda install pytest
        $CONDA/bin/python -m pip install --upgrade pip

        $CONDA/bin/python setup.py install

        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        $CONDA/bin/pytest

        cd ..


  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.8', '3.9' ]
    steps:
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    #
    # - name: Setup conda
    #   uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     auto-update-conda: true
    #     python-version: ${{ matrix.python-version }}
    #
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip

    - name: Checkout
      uses: actions/checkout@v3.0.0
      with:
        repository: harmsm/topiary
        path: topiary

    - name: Install the Python dependencies
      shell: powershell
      run: |

        cd topiary

        C:\Miniconda\condabin\conda.bat env create --file environment.yml
        C:\Miniconda\condabin\conda.bat activate topiary

        C:\Miniconda\condabin\conda.bat install flake8
        C:\Miniconda\condabin\conda.bat install pytest

        python -m pip install --upgrade pip
        ython setup.py install

        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8. --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        pytest

        cd ..
